services:

  redis:
    image: redis:latest
    container_name: trackify_redis
    ports:
      - "6380:6379"


  celery_worker:
    build: .
    container_name: trackify_celery_worker
    command: ["celery", "-A", "app.celery_app.celery_app", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    env_file:
      - .env.development
    depends_on:
      - redis

  celery_beat:
    build: .
    container_name: trackify_celery_beat
    command: ["celery", "-A", "app.celery_app.celery_app", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    env_file:
      - .env.development
    depends_on:
      - redis

volumes:
  db_data: