FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

ENV ENV="production"

EXPOSE 8080

CMD ["celery", "-A", "app.celery_app.celery_app", "beat", "--loglevel=info"]
