services:
  - type: web
    name: trackify-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: SERVICE
        value: web
      - key: ENV
        value: production

  - type: worker
    name: trackify-celery-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: SERVICE
        value: worker
      - key: ENV
        value: production

  - type: worker
    name: trackify-celery-beat
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: SERVICE
        value: beat
      - key: ENV
        value: production
