from sqlmodel import SQLModel, Field


class LLMResponse(SQLModel):
    """
    Schema for the response from the LLM assistant.

    Attributes:
        success (bool): Indicates if the request was successful.
        status (int): HTTP status code.
        message (str): A message describing the result of the request.
        response (str): The response generated by the LLM assistant.
    """

    success: bool = Field(
        default=True, description="Indicates if the request was successful"
    )
    status: int = Field(default=200, description="HTTP status code")
    message: str = Field(
        default="", description="Message describing the result of the request"
    )
    reply: str = Field(
        default="", description="Response generated by the LLM assistant"
    )


class LLMQuery(SQLModel):
    """
    Schema for the user's query to the LLM assistant.

    Attributes:
        message (str): The user's question or message to the assistant.
    """

    message: str = Field(
        description="The user's question or message to the LLM assistant"
    )
