name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: echo "Y" | gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & Push App Image
        run: |
          docker buildx build --push -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify:${{ github.sha }} -f Dockerfile .

      - name: Build & Push Worker Image
        run: |
          docker buildx build --push -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify-worker:${{ github.sha }} -f Dockerfile.worker .

      - name: Build & Push Beat Image
        run: |
          docker buildx build --push -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify-beat:${{ github.sha }} -f Dockerfile.beat .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy trackify-app \
            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify:${{ github.sha }} \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Install GKE Auth Plugin
        run: |
          mkdir -p "$HOME/.config/gcloud"
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Deploy Worker & Beat to GKE
        run: |
          gcloud container clusters get-credentials trackify-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl set image deployment/celery-worker celery-worker=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify-worker:${{ github.sha }}
          kubectl set image deployment/celery-beat celery-beat=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify-beat:${{ github.sha }}
