name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use Google Artifact Registry
        run: echo "Y" | gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push app image
        run: |
          docker buildx build --push -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify:${{ github.sha }} -f Dockerfile .

      - name: Build and push worker image
        run: |
          docker buildx build --push -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify-worker:${{ github.sha }} -f Dockerfile.worker .

      - name: Build and push beat image
        run: |
          docker buildx build --push -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify-beat:${{ github.sha }} -f Dockerfile.beat .

      - name: Install gke-gcloud-auth-plugin
        run: |
          mkdir -p "$HOME/.config/gcloud"
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials trackify-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl set image deployment/trackify-app trackify=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify:${{ github.sha }}
          kubectl set image deployment/trackify-worker worker=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify-worker:${{ github.sha }}
          kubectl set image deployment/trackify-beat beat=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trackify/trackify-beat:${{ github.sha }}
